### PR TITLE
Fix hashbang

### PR DESCRIPTION
**Pull request by bauer-andreas**
# Fix hashbang

## :recycle: Current situation & Problem
Fixes a spelling mistake in the hashbang of the install script that currently makes it unable to run without modifications.

## :gear: Release Notes 
* Fix hashbang

## :books: Documentation
--

## :white_check_mark: Testing
--

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bauer-andreas** [comment]
review request @PSchmiedmayer

**Review by PSchmiedmayer — APPROVED** [review]
Thank you @Supereg 🚀

**Comment by bauer-andreas** [comment]
Don't have write access to the repo, so feel free to merge 👍

**Comment by PSchmiedmayer** [comment]
Sorry about that; I also fixed the permissions issue 👍

**Pull request merged**
